### ISSUE TITLE
Error while building scilpy from source

### ISSUE THREAD

**Issue by zhitao-guo** [scilus/scilpy#1025]
Hello, I encountered an issue while trying to install using `pip install .`. I uploaded an log file and the conda env info is listed as follows:

[build_log.log](https://github.com/user-attachments/files/16829822/build_log.log)

```python
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
bzip2                     1.0.8                h5eee18b_6    defaults
ca-certificates           2024.7.2             h06a4308_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.4.4                h6a678d5_1    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
ncurses                   6.4                  h6a678d5_0    defaults
openssl                   3.0.14               h5eee18b_0    defaults
pip                       24.2            py310h06a4308_0    defaults
python                    3.10.14              h955ad1f_1    defaults
readline                  8.2                  h5eee18b_0    defaults
setuptools                72.1.0          py310h06a4308_0    defaults
sqlite                    3.45.3               h5eee18b_0    defaults
tk                        8.6.14               h39e8969_0    defaults
tzdata                    2024a                h04d1e81_0    defaults
wheel                     0.43.0          py310h06a4308_0    defaults
xz                        5.4.6                h5eee18b_1    defaults
zlib                      1.2.13               h5eee18b_1    defaults
```
Thanks for your help!

**Comment by arnaudbore** [comment]
Hello @zhitao-guo ,

It took us a while to be able to fix this issue but here it is.
Here what you need to run:
```
export SETUPTOOLS_USE_DISTUTILS=stdlib
pip install -e .
```
Please give it a try and if it fixes your issue we will close it.
Arnaud

**Comment by zhitao-guo** [comment]
Hi Arnaud,

Thank you for the solution very much!

For the error: ModuleNotFoundError: No module named 'distutils.msvccompiler', adding the line `export SETUPTOOLS_USE_DISTUTILS=stdlib` works.

For the error: Cython.Compiler.Errors.CompileError:  Scilpy tractanalysis/streamlines_metrics pyx as follows:

```
      Error compiling Cython file:
      ------------------------------------------------------------
      ...

          # This array counts the number of different tracks going through each voxel.
          # Need to keep both the array and the memview on it to be able to
          # reshape and return in the end.
          traversal_tags = np.zeros((n_voxels,), dtype=int)
          cdef np.int_t[:] traversal_tags_v = traversal_tags
               ^
      ------------------------------------------------------------

      scilpy/tractanalysis/streamlines_metrics.pyx:50:9: 'int_t' is not a type identifier

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          traversal_tags = np.zeros((n_voxels,), dtype=int)
          cdef np.int_t[:] traversal_tags_v = traversal_tags

          # This array keeps track of whether the current track has already been
          # flagged in a specific voxel.
          cdef np.int_t[:] touched_tags_v = np.zeros((n_voxels,), dtype=int)
               ^
      ------------------------------------------------------------

      scilpy/tractanalysis/streamlines_metrics.pyx:54:9: 'int_t' is not a type identifier

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

          # Memview for the current edge
          cdef np.double_t[:] cur_edge = np.zeros(3, dtype=np.double)

          # Memview for the coordinates of the current voxel
          cdef np.int_t[:] cur_voxel_coords = np.zeros(3, dtype=int)
               ^
      ------------------------------------------------------------

      scilpy/tractanalysis/streamlines_metrics.pyx:74:9: 'int_t' is not a type identifier
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/guozt/git_repos/scilpy_test/setup.py", line 99, in <module>
          setup(**opts)
        File "/home/guozt/softwares/miniconda3/envs/test/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/home/guozt/softwares/miniconda3/envs/test/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/home/guozt/softwares/miniconda3/envs/test/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/home/guozt/softwares/miniconda3/envs/test/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/guozt/softwares/miniconda3/envs/test/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/guozt/softwares/miniconda3/envs/test/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 398, in run
          self.run_command("build")
        File "/home/guozt/softwares/miniconda3/envs/test/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/guozt/softwares/miniconda3/envs/test/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/guozt/softwares/miniconda3/envs/test/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/guozt/softwares/miniconda3/envs/test/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/guozt/softwares/miniconda3/envs/test/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/guozt/softwares/miniconda3/envs/test/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/guozt/softwares/miniconda3/envs/test/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/guozt/git_repos/scilpy_test/setup.py", line 41, in run
          self.distribution.ext_modules[:] = cythonize(
        File "/home/guozt/git_repos/scilpy_test/.eggs/Cython-3.0.11-py3.10-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/home/guozt/git_repos/scilpy_test/.eggs/Cython-3.0.11-py3.10-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: scilpy/tractanalysis/streamlines_metrics.pyx
```

 I tried to install numpy and then scilpy, and the error can be solved. I'm not clear why I need to install numpy manually firstly.
```
pip install numpy==1.25.*
pip install -e .
```

**Comment by arnaudbore** [comment]
Glad you found a way to make it work, these days we are getting some "weird" issues and struggle a little bit to fix them but if you don't need the latest development work you can always install scilpy 2.0.2 with a simple: `pip install scilpy`

**Comment by zhitao-guo** [comment]
Thanks for your efforts. I will close my issue. Looking forward to better solution of the above error.
