### ISSUE TITLE
scil_decompose_connectivity problem when saving all streamlines

### ISSUE THREAD

**Issue by mdesco** [scilus/scilpy#191]
If I run the decompose command with the all the saving options, it works fine. 

However, if I run this line, with or without invalid coordinates (ic) removed (there are 0 ic streamlines removed), I get the following error.

scil_decompose_connectivity.py Tracking_SET/final_tracks_noloops_ic.trk brainetomme_int16_2.nii.gz connectome_brainetomme --save_raw_connections --save_intermediate --save_discarded -f
/Users/desm2239/my_env/scilpy_public/lib/python3.7/site-packages/scilpy-0.1.dev0-py3.7-macosx-10.14-x86_64.egg/EGG-INFO/scripts/scil_decompose_connectivity.py:208: DeprecationWarning: get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj).

* deprecated from version: 3.0
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
  data_labels = img_labels.get_data()
/Users/desm2239/my_env/scilpy_public/lib/python3.7/site-packages/scilpy-0.1.dev0-py3.7-macosx-10.14-x86_64.egg/EGG-INFO/scripts/scil_decompose_connectivity.py:245: DeprecationWarning: 'ArraySequence.data' property is deprecated.
Please use the 'ArraySequence.get_data()' method instead

* deprecated from version: 3.0
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 4.0
  indices, points_to_idx = uncompress(sft.streamlines, return_mapping=True)
/Users/desm2239/my_env/scilpy_public/lib/python3.7/site-packages/scilpy-0.1.dev0-py3.7-macosx-10.14-x86_64.egg/EGG-INFO/scripts/scil_decompose_connectivity.py:255: DeprecationWarning: get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj).

* deprecated from version: 3.0
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
  img_labels.get_data(), real_labels,
/Users/desm2239/my_env/scilpy_public/lib/python3.7/site-packages/scilpy-0.1.dev0-py3.7-macosx-10.14-x86_64.egg/scilpy/tractanalysis/tools.py:35: RuntimeWarning: invalid value encountered in true_divide
  ray = ray / np.linalg.norm(ray)
/Users/desm2239/my_env/scilpy_public/lib/python3.7/site-packages/dipy/io/stateful_tractogram.py:389: RuntimeWarning: invalid value encountered in less
  if np.any(bbox_corners < 0):
2020-03-29 18:53:09 DINF-DESCOT-04J StatefulTractogram[36423] ERROR Voxel space values lower than 0.0
2020-03-29 18:53:09 DINF-DESCOT-04J StatefulTractogram[36423] ERROR Voxel space values higher than dimensions
Traceback (most recent call last):
  File "/Users/desm2239/my_env/scilpy_public/bin/scil_decompose_connectivity.py", line 4, in <module>
    __import__('pkg_resources').run_script('scilpy==0.1.dev0', 'scil_decompose_connectivity.py')
  File "/Users/desm2239/my_env/scilpy_public/lib/python3.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/desm2239/my_env/scilpy_public/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/Users/desm2239/my_env/scilpy_public/lib/python3.7/site-packages/scilpy-0.1.dev0-py3.7-macosx-10.14-x86_64.egg/EGG-INFO/scripts/scil_decompose_connectivity.py", line 386, in <module>
    main()
  File "/Users/desm2239/my_env/scilpy_public/lib/python3.7/site-packages/scilpy-0.1.dev0-py3.7-macosx-10.14-x86_64.egg/EGG-INFO/scripts/scil_decompose_connectivity.py", line 304, in main
    'raw', in_label, out_label)
  File "/Users/desm2239/my_env/scilpy_public/lib/python3.7/site-packages/scilpy-0.1.dev0-py3.7-macosx-10.14-x86_64.egg/EGG-INFO/scripts/scil_decompose_connectivity.py", line 105, in _save_if_needed
    save_tractogram(sft, out_name)
  File "/Users/desm2239/my_env/scilpy_public/lib/python3.7/site-packages/dipy/io/streamline.py", line 42, in save_tractogram
    raise ValueError('Bounding box is not valid in voxel space, cannot '
ValueError: Bounding box is not valid in voxel space, cannot load a valid file if some coordinates are invalid. Please use the function remove_invalid_streamlines to discard invalid streamlines or set bbox_valid_check to False

Many connections are written and the last one is: 155_231.trk

Data is here if @frheault can test and correct problem.
https://www.dropbox.com/s/4m273c7y1bixj83/decompose_prob.zip?dl=0

Thanks!

**Comment by frheault** [comment]
@arnaudbore can be closed.
