### ISSUE TITLE
scil_compute_seed_density_map.py bug

### ISSUE THREAD

**Issue by mdesco** [scilus/scilpy#221]
@AntoineTheb pense-tu que tu peux tester/checker ce bug.
Les bundles sortent de recobundle scilpy de Francois. Le bundle en question (AF) n'a aucune invalid coordinates. Il visualise bien avec tous les outils...

Data: https://www.dropbox.com/s/b443bzf5z9bmyvj/bug_antoine.zip?dl=0

Merci

scil_compute_seed_density_map.py AF_L_m.trk yo.nii.gz
Traceback (most recent call last):
  File "/Users/desm2239/my_env/scilpy_public/bin/scil_compute_seed_density_map.py", line 4, in <module>
    __import__('pkg_resources').run_script('scilpy==0.1.dev0', 'scil_compute_seed_density_map.py')
  File "/Users/desm2239/my_env/scilpy_public/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/desm2239/my_env/scilpy_public/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/Users/desm2239/my_env/scilpy_public/lib/python3.6/site-packages/scilpy-0.1.dev0-py3.6-macosx-10.9-x86_64.egg/EGG-INFO/scripts/scil_compute_seed_density_map.py", line 97, in <module>
    main()
  File "/Users/desm2239/my_env/scilpy_public/lib/python3.6/site-packages/scilpy-0.1.dev0-py3.6-macosx-10.9-x86_64.egg/EGG-INFO/scripts/scil_compute_seed_density_map.py", line 88, in main
    seed_density[tuple(seed_voxel)] += 1
IndexError: index 161 is out of bounds for axis 1 with size 144

**Comment by AntoineTheb** [comment]
Addressed in #225 !
