### ISSUE TITLE
Apply transform to hdf5 error when DPP are present

### ISSUE THREAD

**Issue by frheault** [scilus/scilpy#960]
There is a raise NotImplementedError("DPP data? Other?") at line 111 of the file scilpy/io/hdf5.py that makes connectoflow crash when we get to the script scil_tractogram_apply_transform_to_hdf5.py

**Comment by gagnonanthony** [comment]
I just encountered the same issue when trying to save .trk from an hdf5 with DPP (decompose after running COMMIT). Instead of opening a new issue, I decided to mention it here! @frheault @arnaudbore

**Comment by gagnonanthony** [comment]
Error message: 
```bash
Traceback (most recent call last):
  File "/Users/anthonygagnon/envs/scilus3.10/bin/scil_save_connections_from_hdf5.py", line 33, in <module>
    sys.exit(load_entry_point('scilpy', 'console_scripts', 'scil_save_connections_from_hdf5.py')())
  File "/Users/anthonygagnon/code/scilpy/scilpy/io/deprecator.py", line 93, in _wrapper
    return _raise_warning(_block(header, msg_length),
  File "/Users/anthonygagnon/code/scilpy/scilpy/io/deprecator.py", line 54, in _raise_warning
    return func(*args, **kwargs)
  File "/Users/anthonygagnon/code/scilpy/scripts/legacy/scil_save_connections_from_hdf5.py", line 17, in main
    new_main()
  File "/Users/anthonygagnon/code/scilpy/scripts/scil_tractogram_convert_hdf5_to_trk.py", line 130, in main
    sft, _ = reconstruct_sft_from_hdf5(hdf5_file, key,
  File "/Users/anthonygagnon/code/scilpy/scilpy/io/hdf5.py", line 120, in reconstruct_sft_from_hdf5
    raise NotImplementedError("DPP data? Other?")
NotImplementedError: DPP data? Other?
```

Comes from here (`scilpy.io.hdf5.py`):
```python
                    else:
                        if load_dpp:
                            raise NotImplementedError(
                                "Don't know how to load dpp yet.")
                        raise NotImplementedError("DPP data? Other?") # <--- HERE
```

**Comment by frheault** [comment]
Are you on a old version, this load_dpp flag should be false in all scilpy script (and be false by default)

**Comment by gagnonanthony** [comment]
Nope, up-to-date with the master. I just retested to be sure, and the error persists. @frheault
